---
title: "Etapa 3 - Análisis de Discrminante"
author: "Equipo 5 - MA2003B.101"
date: "2023-09-01"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Preparación del Ambiente
```{r}
# Importar Librarías
library(MASS)
set.seed(12345)
```

### Cargar Datos
```{r}
# Etiquetas de clase
flags = subset(read.csv("FLAGS.csv", encoding = "UTF-8"), select = -1)
head(flags)

# Set de Datos
data = subset(read.csv("DATOS HISTÓRICOS 2022_2023_TODAS ESTACIONES CONCATENADOS LIMPIOS.csv", encoding = "UTF-8"), select = -1)
head(data)
```
### Restructurar Dataset
```{r}
# Variables predictoras
predictive = subset(data, select=c(4, 5, 6, 7, 8, 9, 10))
head(predictive)
```

```{r}
# Unificar set de datos | Etiquetas de clase & Variables predictoras
data_merged = cbind(flags, predictive)

head(data_merged)
```

### Segmentación de los Datos
```{r}
#Usar 70% de los datos para entrenamiento y el 30% restante para pruebas
sample = sample(c(TRUE, FALSE), nrow(data_merged), replace=TRUE, prob=c(0.7,0.3))

train = data_merged[sample,]
test = data_merged[!sample,]
```

```{r}
summary(train)
```




### Modelado | Análisis Discriminante Lineal
##### Modelo: PM2.5
```{r}
# Modelado
lda.model.PM2.5 = lda(PM2.5~PRS+RH+TOUT+WSR+WDR+RAINF+SR, data=train)
lda.model.PM2.5

# Predicciones
predictions_PM25 = predict(lda.model.PM2.5, newdata = test)
predicted_classPM25 = predictions_PM25$class

cat("\n\nMétricas de Evaluación: \n\n")
# Matriz de Confusión
cat("Matriz de confusión:\n")
T1 = table(pred=predicted_classPM25, true=test$PM2.5)
rownames(T1) = c("G", "B")
colnames(T1) = c("G", "B")
T1
cat("\nPorcentaje de observaciones clasificadas erróneamente: ", 1-mean(predicted_classPM25==test$PM2.5))
precission1 = T1[2,2]/(T1[2,2]+T1[2,1])
cat("\nPrecisión: ", precission1)
recall1 = T1[2,2]/(T1[2,2]+T1[1,2])
cat("\nSensbilidad: ", recall1)
cat("\nF1 Scores: ", 2*(precission1*recall1)/(precission1+recall1))
```
##### Modelo: PM10
```{r}
# Modelado
lda.model.PM10 = lda(PM10~PRS+RH+TOUT+WSR+WDR+RAINF+SR, data=train)
lda.model.PM10

# Predicciones
predictions_PM10 = predict(lda.model.PM10, newdata = test)
predicted_classPM10 = predictions_PM10$class


cat("\n\nMétricas de Evaluación: \n\n")
# Matriz de Confusión
cat("Matriz de confusión:\n")
T2 = table(pred=predicted_classPM10, true=test$PM10)
rownames(T2) = c("G", "B")
colnames(T2) = c("G", "B")
T2
cat("\nPorcentaje de observaciones clasificadas erróneamente: ", 1-mean(predicted_classPM10==test$PM10))
precission2 = T2[2,2]/(T2[2,2]+T2[2,1])
cat("\nPrecisión: ", precission2)
recall2 = T2[2,2]/(T2[2,2]+T2[1,2])
cat("\nSensbilidad: ", recall2)
cat("\nF1 Scores: ", 2*(precission2*recall2)/(precission2+recall2))
```

##### Modelo: O3
La carencia de multiples etiquetas de clase imposibilita el modelado.


